/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InventoryState.java
 *
 * Created on 12 Apr 11, 19:02:09
 */

package plantmon.states;

import javax.swing.JLabel;
import plantmon.entity.Inventory;
import plantmon.entity.movingObject.Player;

/**
 *
 * @author asus
 */
public class InventoryState extends ParentState {
    Player player;
    /** Creates new form InventoryState */
    public InventoryState(Object[] args) {
        super();
        ID = INVENTORY;
        if (args[0] instanceof Player)
            this.player = (Player)args[0];
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane6 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Pulmosis = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(640, 480));

        jTabbedPane6.setName("jTabbedPane6"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(4, 4));
        farm = Game.instance().getInventory().getFarmItem();
        for (int i=0; i<farm.getSize(); i++){
            jPanel1.add(new JLabel(farm.getItem(i).getName()+" "+farm.getJumlah(i)));
        }
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(plantmon.PlantmonApp.class).getContext().getResourceMap(InventoryState.class);
        jTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(4, 4));
        farm = Game.instance().getInventory().getFoodItem();
        for (int i=0; i<farm.getSize(); i++){
            jPanel2.add(new JLabel(farm.getItem(i).getName()+" "+farm.getJumlah(i)));
        }
        jTabbedPane1.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(4, 4));
        farm = Game.instance().getInventory().getWarItem();
        for (int i=0; i<farm.getSize(); i++){
            jPanel3.add(new JLabel(farm.getItem(i).getName()+" "+farm.getJumlah(i)));
        }
        jTabbedPane1.addTab(resourceMap.getString("jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(4, 4));
        farm = Game.instance().getInventory().getArmorItem();
        for (int i=0; i<farm.getSize(); i++){
            jPanel4.add(new JLabel(farm.getItem(i).getName()+" "+farm.getJumlah(i)));
        }
        jTabbedPane1.addTab(resourceMap.getString("jPanel4.TabConstraints.tabTitle"), jPanel4); // NOI18N

        jTabbedPane6.addTab(resourceMap.getString("jTabbedPane1.TabConstraints.tabTitle"), jTabbedPane1); // NOI18N

        Pulmosis.setName("Pulmosis"); // NOI18N

        javax.swing.GroupLayout PulmosisLayout = new javax.swing.GroupLayout(Pulmosis);
        Pulmosis.setLayout(PulmosisLayout);
        PulmosisLayout.setHorizontalGroup(
            PulmosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        PulmosisLayout.setVerticalGroup(
            PulmosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab(resourceMap.getString("Pulmosis.TabConstraints.tabTitle"), Pulmosis); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText(String.valueOf(Game.instance().getMoney()));
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
            .addComponent(jTabbedPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Game.instance().returnTo(FARMSTATE);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pulmosis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private Inventory farm;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane6;
    // End of variables declaration//GEN-END:variables

}
